name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: npm install
      - name: Build project
        run: npm run-script build
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.d1407bd8-1026-4388-aa6e-de5672c2c268}}
          heroku_app_name: ${{secrets.biaawc-web-app}
          heroku_email: ${{secrets.alexander.pres.coding@gmail.com}}
          procfile: 'web: npm start'
